name: gnn
channels:
  # These do NOT commute!
  - pytorch
  - nvidia
  - pyg
  - ostrokach-forge
  - conda-forge
  - scikit-learn
dependencies:
  - python >= 3.10
  - pytorch >= 2
  - pytorch-cuda >= 11.8
  - pyg >= 2.3.0
  - pytorch-cluster
  - optuna
  - wandb
  - numpy < 2
  - pandas
  - scikit-learn
  - pip
  - jupyter
